### PR TITLE
Demo server: Bump versions for 540 upgrade.

### PR DESCRIPTION
**Pull request by kennethgillen**
OMERO and Web versions for demo sever prod playbook incremented for demo server upgrade.

### CODE REVIEW

**Comment by kennethgillen** [comment]
I'm not sure what, if anything, Travis is doing here. Perhaps we can sort that out later? Travis didn't go well on https://github.com/openmicroscopy/prod-playbooks/pull/7/commits

**Comment by joshmoore** [comment]
Looks green to me (syntax check etc). Are you pushing the 5.4.1 changes to this PR as well or do you want to get it in as is?

**Comment by kennethgillen** [comment]
I'd be inclined to get in as the recorded state of the 5.4.0 upgrade. Then potentially getting more Travis etc into the mix for 5.4.1.

**Comment by joshmoore** [comment]
WFM :+1:

**Comment by sbesson** [comment]
Re https://github.com/openmicroscopy/prod-playbooks/pull/11#issuecomment-347577624, @josh said it all. As the syntax check in `demo` seems to be green, probably worth removing it from the allowed failures in https://github.com/openmicroscopy/prod-playbooks/blob/master/.travis.yml#L38 now too.

**Pull request merged**
