### PR TITLE
Bump OMERO version to 5.4.2

### PR DESCRIPTION
**Pull request by joshmoore**
Updated all playbooks together.

cc: @pwalczysko @kennethgillen

### CODE REVIEW

**Comment by kennethgillen** [comment]
👍  - thanks @joshmoore.

**Comment by joshmoore** [comment]
np

**Comment by pwalczysko** [comment]
@joshmoore sounds great, sorry for comming a bit late to this. Will try now to arrange myself so that I work from this repo (as opposed from the examples repo) as discussed on trello

**Comment by joshmoore** [comment]
:+1: Let me know when, where & how I can help.

**Pull request merged**
