### PR TITLE
Bumping prod-playbooks NS & Demo to 5.4.6

### PR DESCRIPTION
**Pull request by kennethgillen**
Production servers upgraded to latest OMERO version, and network role bumped for all of `prod-playbooks`.

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1892](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1892/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1892/consoleText) for more details.
Possible conflicts:
  - PR #62 kennethgillen 'pub-omero equivalent to demoserver'
    - ome-demoserver.yml

--conflicts

**Comment by sbesson** [comment]
Has this been deployed to production yet i.e. do we have logs? If yes, i'd vote for getting this is as this reflects the state of prod servers and fix the conflicts on #62 (where changes were requested).

**Comment by kennethgillen** [comment]
Yes,

Deployed live: 

ome-demoserver: ara:///reports/dcb55552-a03c-4643-a378-a4bd6e6f43f2.html
ns-web: ara:///reports/1ba0f44c-7e33-4670-b999-6305cda59769.html
ns-web-pub: ara:///reports/997b97c8-96f0-4d65-a404-cbb61b1c4231.html

I'd also prefer to make changes to the pub-omero PR.

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by kennethgillen** [comment]
Updated. Sorry @snoopycrimecop.

**Pull request merged**
