### PR TITLE
Travis syntax check and lint

### PR DESCRIPTION
**Pull request by manics**
Adds syntax checking and ansible-lint.

This is expected to fail on travis with the current playbooks.

### CODE REVIEW

**Comment by sbesson** [comment]
Activated Travis. Closing/reopening to validate this PR.

**Comment by sbesson** [comment]
Some syntax issues (a lot of trailing whitespaces). What is the next action here? Should we cleanup existing playbooks before adding anything enw?

**Comment by manics** [comment]
It's a matrix build, so new playbooks can be tested and verified to pass without needing to fix existing ones immediately.

**Comment by sbesson** [comment]
That's fine, should we mark the existing ones as expected to fail in that case and we'll review them as we modify them?

**Comment by manics** [comment]
updated

**Pull request merged**
