### PR TITLE
OME OMERO demo server 5.3.4 upgrade

### PR DESCRIPTION
**Pull request by kennethgillen**
Bump version to 5.3.4, add docs for upgrade usage.

Switch to 'localhost' which helps when testing this playbook elsewhere, otherwise web interface points to live demo server.

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1606](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1606/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1606/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .travis.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1607](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1607/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1607/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .travis.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1608](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1608/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1608/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .travis.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1609](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1609/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1609/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .travis.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1610](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1610/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1610/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .travis.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1611](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1611/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1611/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .travis.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1612](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1612/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1612/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .travis.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1613](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1613/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1613/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .travis.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1614](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1614/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1614/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .travis.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1615](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1615/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1615/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .travis.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1616](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1616/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1616/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .travis.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1617](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1617/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1617/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .travis.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1618](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1618/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1618/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .travis.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1619](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1619/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1619/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .travis.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1620](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1620/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1620/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .travis.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1621](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1621/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1621/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .travis.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1622](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1622/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1622/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .travis.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1623](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1623/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1623/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .travis.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1624](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1624/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1624/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .travis.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1625](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1625/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1625/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .travis.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1626](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1626/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1626/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .travis.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1627](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1627/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1627/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .travis.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1628](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1628/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1628/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .travis.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1629](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1629/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1629/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .travis.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1630](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1630/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1630/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .travis.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1631](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1631/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1631/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .travis.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1632](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1632/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1632/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .travis.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1633](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1633/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1633/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .travis.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1634](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1634/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1634/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .travis.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1635](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1635/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1635/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .travis.yml

--conflicts

**Comment by kennethgillen** [comment]
I've merged current master .travis.yml, thanks @jburel.

Since linting was addressed, merging to allow the next bump to 5.4.0.

**Comment by jburel** [comment]
Will you have another PR for 5.3.5?

**Comment by kennethgillen** [comment]
@jburel - yes, and for Nightshade too. 

I'll do the Nightshade and Demo to 5.4.0 on a separate single PR, and then work out how to deal with merging it all after the fact.

Should have been a single PR last time I realised after the fact, for the two systems.

**Comment by jburel** [comment]
Run ``ansible-lint ome-demoserver.yml `` locally no error.
The lint change requested by @sbesson has been done
It was also suggested to remove it from the list of failure, is that possible?

**Comment by jburel** [comment]
Not ready to be moved out of the allow_failures matrix

**Comment by sbesson** [comment]
This playbook is modified in #6. Should these PRs be unified into a single one?

**Pull request merged**
