### PR TITLE
Public images

### PR DESCRIPTION
**Pull request by sbesson**
Exposes another set of public images under http://downloads.openmicroscopy.org/images/

### CODE REVIEW

**Comment by joshmoore** [comment]
Do you already have a test run? In general, seems fine, but some files are missing no?

```
[jamoore@idr0-slot3 curated]$ find . -maxdepth 3 -name public
./olympus-oir/public
./tiff/public
./amira/public
./trestle/public
./hamamatsu-vms/public
./perkinelmer-operetta/public
./vectra-qptiff/public
./nd2/public
./mrc/public
./ecat7/public
./hamamatsu/public
./svs/public
./micromanager/public
./incell3000/public
./cellomics/public
./png/public
./nrrd/public
./imaris/public
./incell/public
./leica-scn/public
./deltavision/public
./nifti/public
./becker-hickl-spc/public
./dicom/public
./leica-lif/public
[jamoore@idr0-slot3 curated]$ find incell/public/ leica-scn/public/ mrc/public/ perkinelmer-operetta/public/ trestle/public/ -iname readme.txt -o -iname COPYING
trestle/public/openslide/readme.txt
trestle/public/openslide/COPYING
```

**Comment by sbesson** [comment]
Additional readme/licensing added to the various folders

```
[sbesson@idr0-slot3 curated]$ find incell/public/ leica-scn/public/ mrc/public/ perkinelmer-operetta/public/ trestle/public/ -iname readme.txt -o -iname COPYING
leica-scn/public/openslide/readme.txt
mrc/public/EMDB/readme.txt
trestle/public/openslide/readme.txt
trestle/public/openslide/COPYING
```

and run the playbook in check-mode

```
(ansible) sbesson@lifesci-80612:prod (master_merge_trigger) $ ansible-playbook -i ../ansible/inventory/prod-hosts --ask-become -C playbooks/release/public-images.yml 
SUDO password: 

PLAY [idr0-slot3.openmicroscopy.org] **************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************************
ok: [idr0-slot3.openmicroscopy.org]

TASK [check public images] ************************************************************************************************************************
ok: [idr0-slot3.openmicroscopy.org] => (item={u'dest': u'AmiraMesh', u'src': u'../../../repos/curated/amira/public/'})
ok: [idr0-slot3.openmicroscopy.org] => (item={u'dest': u'Cellomics', u'src': u'../../../repos/curated/cellomics/public/'})
ok: [idr0-slot3.openmicroscopy.org] => (item={u'dest': u'DICOM', u'src': u'../../../repos/curated/dicom/public/'})
ok: [idr0-slot3.openmicroscopy.org] => (item={u'dest': u'DV', u'src': u'../../../repos/curated/deltavision/public/'})
ok: [idr0-slot3.openmicroscopy.org] => (item={u'dest': u'ECAT7', u'src': u'../../../repos/curated/ecat7/public/'})
ok: [idr0-slot3.openmicroscopy.org] => (item={u'dest': u'gateway_tests/big.tiff', u'src': u'../../../../repos/curated/samples/carlos/big.tiff'})
ok: [idr0-slot3.openmicroscopy.org] => (item={u'dest': u'gateway_tests/CHOBI_d3d.dv', u'src': u'../../../../repos/curated/samples/ome/CHOBI_d3d.dv'})
ok: [idr0-slot3.openmicroscopy.org] => (item={u'dest': u'gateway_tests/tinyTest.d3d.dv', u'src': u'../../../../repos/curated/samples/ome/tinyTest.d3d.dv'})
ok: [idr0-slot3.openmicroscopy.org] => (item={u'dest': u'Hamamatsu-NDPI', u'src': u'../../../repos/curated/hamamatsu/public'})
ok: [idr0-slot3.openmicroscopy.org] => (item={u'dest': u'Hamamatsu-VMS', u'src': u'../../../repos/curated/hamamatsu-vms/public/'})
ok: [idr0-slot3.openmicroscopy.org] => (item={u'dest': u'HCS/BBBC', u'src': u'../../../../repos/curated/cellomics/public/'})
ok: [idr0-slot3.openmicroscopy.org] => (item={u'dest': u'HCS/INCELL2000', u'src': u'../../../../repos/curated/incell/public/'})
ok: [idr0-slot3.openmicroscopy.org] => (item={u'dest': u'HCS/Operetta', u'src': u'../../../../repos/curated/perkinelmer-operetta/public/'})
ok: [idr0-slot3.openmicroscopy.org] => (item={u'dest': u'Imaris-IMS', u'src': u'../../../repos/curated/imaris/public/'})
changed: [idr0-slot3.openmicroscopy.org] => (item={u'dest': u'InCell2000', u'src': u'../../../repos/curated/incell/public/'})
ok: [idr0-slot3.openmicroscopy.org] => (item={u'dest': u'InCell3000', u'src': u'../../../repos/curated/incell3000/public/'})
ok: [idr0-slot3.openmicroscopy.org] => (item={u'dest': u'Leica-LIF', u'src': u'../../../repos/curated/leica-lif/public/'})
changed: [idr0-slot3.openmicroscopy.org] => (item={u'dest': u'Leica-SCN', u'src': u'../../../repos/curated/leica-scn/public/'})
ok: [idr0-slot3.openmicroscopy.org] => (item={u'dest': u'Micro-Manager', u'src': u'../../../repos/curated/micromanager/public/'})
changed: [idr0-slot3.openmicroscopy.org] => (item={u'dest': u'MRC', u'src': u'../../../repos/curated/mrc/public/'})
ok: [idr0-slot3.openmicroscopy.org] => (item={u'dest': u'ND2', u'src': u'../../../repos/curated/nd2/public/'})
ok: [idr0-slot3.openmicroscopy.org] => (item={u'dest': u'NIfTI', u'src': u'../../../repos/curated/nifti/public/'})
ok: [idr0-slot3.openmicroscopy.org] => (item={u'dest': u'NRRD', u'src': u'../../../repos/curated/nrrd/public/'})
ok: [idr0-slot3.openmicroscopy.org] => (item={u'dest': u'Olympus-OIR', u'src': u'../../../repos/curated/olympus-oir/public/'})
ok: [idr0-slot3.openmicroscopy.org] => (item={u'dest': u'OME-TIFF', u'src': u'../../../repos/curated/ome-tiff/ome-schemas/'})
ok: [idr0-slot3.openmicroscopy.org] => (item={u'dest': u'OME-XML', u'src': u'../../../repos/curated/ome-xml/ome-schemas/'})
changed: [idr0-slot3.openmicroscopy.org] => (item={u'dest': u'Operetta', u'src': u'../../../repos/curated/perkinelmer-operetta/public/'})
ok: [idr0-slot3.openmicroscopy.org] => (item={u'dest': u'PNG', u'src': u'../../../repos/curated/png/public/'})
ok: [idr0-slot3.openmicroscopy.org] => (item={u'dest': u'SPC-FIFO', u'src': u'../../../repos/curated/becker-hickl-spc/public/'})
ok: [idr0-slot3.openmicroscopy.org] => (item={u'dest': u'SVS', u'src': u'../../../repos/curated/svs/public/'})
ok: [idr0-slot3.openmicroscopy.org] => (item={u'dest': u'TIFF', u'src': u'../../../repos/curated/tiff/public/'})
changed: [idr0-slot3.openmicroscopy.org] => (item={u'dest': u'Trestle', u'src': u'../../../repos/curated/trestle/public/'})
ok: [idr0-slot3.openmicroscopy.org] => (item={u'dest': u'u-track', u'src': u'../../../repos/curated/zip/u-track/'})
ok: [idr0-slot3.openmicroscopy.org] => (item={u'dest': u'Vectra-QPTIFF', u'src': u'../../../repos/curated/vectra-qptiff/public/'})

PLAY RECAP ****************************************************************************************************************************************
idr0-slot3.openmicroscopy.org : ok=2    changed=1    unreachable=0    failed=0   
````

**Comment by jburel** [comment]
folder like InCell, PerkinElmer will benefit from a readme 
containing info on how to load the file in batch

**Comment by sbesson** [comment]
@jburel agreed although I think such information is really generic for any format with a lot of data. My concern with a per-format readme is that it is not scalable or maintenable. Other suggestions could include putting such a files:
- under https://downloads.openmicroscopy.org/images
- under https://downloads.openmicroscopy.org/
- under https://www.openmicroscopy.org in the context of a page promoting these public samples

In terms of the command, the best I have found with the current structure would be a recursive `wget` e.g.

```
wget -r --mirror -np --wait 5 -e --reject="index.html*" -e robots=off http://downloads.openmicroscopy.org/images/PNG/will/WesternBlots/
```

**Comment by sbesson** [comment]
Briefly following on the conversation above, https://github.com/openmicroscopy/prod-playbooks/pull/72#issuecomment-398745301 certainly needs to be addressed as the burden is on consumers at the moment for large filesets. Options can range from better instructions under downloads.openmicroscopy.org or the main OME website to complete alternative methods (Zenodo, public buckets...).

Solving the exposition and downloading of public images is outwith the initial scope of this PR and most likely an effort that should be scoped by a team. Assuming the last commit addresses the outstanding issues raised https://github.com/openmicroscopy/prod-playbooks/pull/72#issuecomment-395729764, merging and deploying for indidivual MRC, Leica SCN and Trestle samples.

**Pull request merged**
