### PR TITLE
Gbi outreach

### PR DESCRIPTION
**Pull request by jburel**
Re-deploy outreach for Wednesday session

Few dependencies added to the requirement file otherwise it was not possible to run the playbook

cc @manics @pwalczysko

### CODE REVIEW

**Comment by manics** [comment]
Looks OK to me

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [TRAINING-merge#105](https://ci.openmicroscopy.org/job/TRAINING-merge/105/). See the [console output](https://ci.openmicroscopy.org/job/TRAINING-merge/105/consoleText) for more details.
Possible conflicts:
  - PR #68 manics 'Bump omero web role'
    - requirements.yml
  - PR #93 manics 'jupyterhub-training-alt fallback server'
    - requirements.yml
  - PR #98 manics 'Update omedev bootstrap playbook'
    - requirements.yml

--conflicts

**Comment by pwalczysko** [comment]
This has conflicts. 

I think the changes are reasonable.
I will try to run this playbook on outreach, but only next week, as we promised to keep the outreach up for the Australia-GBI-course participants.

**Comment by jburel** [comment]
The conflict is due to the fact one of the changes in #68  was inadvertently included in https://github.com/openmicroscopy/prod-playbooks/pull/102
I will look at it tomorrow

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [TRAINING-merge#110](https://ci.openmicroscopy.org/job/TRAINING-merge/110/). See the [console output](https://ci.openmicroscopy.org/job/TRAINING-merge/110/consoleText) for more details.
Possible conflicts:
  - PR #68 manics 'Bump omero web role'
    - requirements.yml
  - PR #93 manics 'jupyterhub-training-alt fallback server'
    - requirements.yml
  - PR #98 manics 'Update omedev bootstrap playbook'
    - requirements.yml

--conflicts

**Comment by jburel** [comment]
@pwalczysko if you could have a look so I can tag the training repo for GBI

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#2025](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/2025/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/2025/consoleText) for more details.
Possible conflicts:
  - PR #93 manics 'jupyterhub-training-alt fallback server'
    - requirements.yml
  - PR #98 manics 'Update omedev bootstrap playbook'
    - requirements.yml

--conflicts

**Comment by pwalczysko** [comment]
Run in check mode (which failed). Run again in non-check mode. Worked fine.

Ready to merge.

**Comment by pwalczysko** [comment]
Well, ready to merge after the conflicts are sorted out.

**Comment by jburel** [comment]
@pwalczysko it conflicts with @manics PR since all the PRs have touched the requirements file.
I discussed with @manics, we opted to merge this PR and @manics will sort out the conflicts in his PRs

**Comment by jburel** [comment]
@pwalczysko did you update the version of the roles?
This should no longer fail in checkmode
``ansible-playbook playbooks/omero/training-server/playbook.yml -i ../ansible/inventory/prod-hosts --check --become
``
``
PLAY RECAP **************************************************************************************************************************************************************
outreach.openmicroscopy.org : ok=125  changed=14   unreachable=0    failed=0   
``

**Comment by pwalczysko** [comment]
Now it works also in check mode. Thanks @jburel @manics

**Pull request merged**
