### PR TITLE
Outreach monitoring

### PR DESCRIPTION
**Pull request by manics**
Add playbook for monitoring outreach server (prometheus and grafana). This is all public for the demo, in future we may want to protect it. Note for docker routing reasons although the apps are proxied through nginx they also expose some docker ports, so if we decide to block grafana and prometheus in future we will need to review this.

- [x] --depends-on https://github.com/openmicroscopy/prod-playbooks/pull/69 (nested nginx includes)
- [x] --depends-on https://github.com/IDR/omero-prometheus-tools/pull/3 (omero prometheus monitoring scripts)
- [x] --depends-on https://github.com/openmicroscopy/ansible-role-prometheus/pull/5 (Prometheus version)
- [x] --depends-on https://github.com/openmicroscopy/ansible-role-prometheus-jmx/pull/2 (Prometheus JMX version)
- [x] --depends-on https://github.com/openmicroscopy/ansible-role-prometheus-node/pull/2 (Prometheus Node Exporter version)
- [x] --depends-on https://github.com/openmicroscopy/ansible-role-prometheus-postgres/pull/3 (Prometheus Postgres version)
- ~~fix monitoring.yml conflict in playbook.yml after #69 is merged~~
- [x] transfer https://github.com/manics/ansible-role-omero-prometheus-exporter
- [x] transfer https://github.com/manics/ansible-role-omero-web-django-prometheus

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [TRAINING-merge#24](https://ci.openmicroscopy.org/job/TRAINING-merge/24/). See the [console output](https://ci.openmicroscopy.org/job/TRAINING-merge/24/consoleText) for more details.
Possible conflicts:
  - PR #69 manics 'omero-web nginx nested includes and letsencrypt'
    - omero/training-server/playbook.yml

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1907](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1907/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1907/consoleText) for more details.
Possible conflicts:
  - PR #69 manics 'omero-web nginx nested includes and letsencrypt'
    - omero/training-server/playbook.yml

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [TRAINING-merge#25](https://ci.openmicroscopy.org/job/TRAINING-merge/25/). See the [console output](https://ci.openmicroscopy.org/job/TRAINING-merge/25/consoleText) for more details.
Possible conflicts:
  - PR #69 manics 'omero-web nginx nested includes and letsencrypt'
    - omero/training-server/playbook.yml

--conflicts

**Comment by joshmoore** [comment]
General question from me regarding how much role-ification is possible / suggestible here.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [TRAINING-merge#30](https://ci.openmicroscopy.org/job/TRAINING-merge/30/). See the [console output](https://ci.openmicroscopy.org/job/TRAINING-merge/30/consoleText) for more details.
Possible conflicts:
  - PR #69 manics 'omero-web nginx nested includes and letsencrypt'
    - omero/training-server/playbook.yml
  - Upstream changes
    - omero/training-server/playbook.yml

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1913](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1913/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1913/consoleText) for more details.
Possible conflicts:
  - PR #69 manics 'omero-web nginx nested includes and letsencrypt'
    - omero/training-server/playbook.yml
  - Upstream changes
    - omero/training-server/playbook.yml

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [TRAINING-merge#35](https://ci.openmicroscopy.org/job/TRAINING-merge/35/). See the [console output](https://ci.openmicroscopy.org/job/TRAINING-merge/35/consoleText) for more details.
Possible conflicts:
  - PR #69 manics 'omero-web nginx nested includes and letsencrypt'
    - omero/training-server/playbook.yml
  - Upstream changes
    - omero/training-server/playbook.yml

--conflicts

**Comment by manics** [comment]
I've attempted to extract the agents (exporters) only from this PR into https://github.com/openmicroscopy/prod-playbooks/pull/75. I'll need to check whether it's correct or not.

**Comment by manics** [comment]
I'm going to assume no one's relying on the prometheus/grafana servers on outreach (the agents are still active and handled elsewhere)

**Pull request closed without merging**
