### PR TITLE
Molecule 1 → Molecule 2

### PR DESCRIPTION
**Pull request by manics**
These are more or less the minimum changes required to switch to molecule 2. Each scenario now has it's own `molecule.yml` file instead of using the shared `molecule-syntaxcheck.yml` file which should make switching a playbook to a full test easier in future.

Apart from a couple of minor changes for ansible-lint no attempt has been made to be fully compliant with the molecule 2 linting. For example `yamllint` has been disabled in all molecule.yml files. Anyone is welcome to fix this in future.

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [TRAINING-merge#265](https://ci.openmicroscopy.org/job/TRAINING-merge/265/). See the [console output](https://ci.openmicroscopy.org/job/TRAINING-merge/265/consoleText) for more details.
Possible conflicts:
  - PR #93 manics 'jupyterhub-training-alt fallback server'
    - .travis.yml
  - PR #155 pwalczysko 'Remove the conditionals between ns and ns-pub'
    - nightshade-webclients.yml

--conflicts

**Comment by sbesson** [comment]
In general :+1: to:

- bumping the meta-package to `ome-ansible-molecule`
- upgrading tests to Molecule 2 
- aligning the Ansible version used for testing of these playbooks with the one used elsewhere like IDR
- migrating playbook-specific logic away from `.travis.yml` into individual scenarios

Most changes are modifiying the testing infrastructure only. Once Travis is green and we have established the same sequence of tests are executed, no objection to merging this and starting to review and enable more steps of the sequences per playbook or group of playbooks separately.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [TRAINING-merge#266](https://ci.openmicroscopy.org/job/TRAINING-merge/266/). See the [console output](https://ci.openmicroscopy.org/job/TRAINING-merge/266/consoleText) for more details.
Possible conflicts:
  - PR #155 pwalczysko 'Remove the conditionals between ns and ns-pub'
    - nightshade-webclients.yml

--conflicts

**Comment by manics** [comment]
I checked with @pwalczysko yesterday, he's happy for this to go in and we'll rebase #155

**Comment by sbesson** [comment]
:+1: I was about to comment that in addition to my review, it would be good to have a sign off from the other consumers of these playbooks incl. @pwalczysko and @jburel to make sure we are all on the same page.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#2257](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/2257/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/2257/consoleText) for more details.
Possible conflicts:
  - Conflict detection failed
    - None

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [TRAINING-merge#267](https://ci.openmicroscopy.org/job/TRAINING-merge/267/). See the [console output](https://ci.openmicroscopy.org/job/TRAINING-merge/267/consoleText) for more details.
Possible conflicts:
  - PR #155 pwalczysko 'Remove the conditionals between ns and ns-pub'
    - nightshade-webclients.yml

--conflicts

**Comment by manics** [comment]
> although I am unclear about the sequence inversion for some of the configurations.

I think it's a bug in molecule 2.19, it might or might not be fixed in a later version: https://github.com/openmicroscopy/prod-playbooks/pull/162/files#diff-450eb832dad0981033fd3aa76f784094R43

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#2259](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/2259/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/2259/consoleText) for more details.
Possible conflicts:
  - Conflict detection failed
    - None

--conflicts

**Comment by joshmoore** [comment]
If I understand correctly, all test infrastructure is now cleanly under `molecule/`. :+1: Might be worth stating as much either in a top-level README or a special README under that directory.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [TRAINING-merge#269](https://ci.openmicroscopy.org/job/TRAINING-merge/269/). See the [console output](https://ci.openmicroscopy.org/job/TRAINING-merge/269/consoleText) for more details.
Possible conflicts:
  - PR #155 pwalczysko 'Remove the conditionals between ns and ns-pub'
    - nightshade-webclients.yml

--conflicts

**Comment by manics** [comment]
How's this?

**Comment by joshmoore** [comment]
Very nice. demo & dundeeomero are swapped, but other than that, :+1: Thanks.

**Pull request merged**
