### PR TITLE
Add new playbook to update public OME presentations

### PR DESCRIPTION
**Pull request by sbesson**
/cc @jburel

### CODE REVIEW

**Comment by sbesson** [comment]
Executed in check-mode (see `reports/612a4ac0-6ced-4f92-8ae9-7ced50d6586b.html`).
For all the playbooks creating/adding static content, I am considering adding an extra task to all playbooks outside check-mode to create a GPFS snapshot following their execution.

**Comment by manics** [comment]
Looks fine.

`$ git status --ignored` in the existing checkout shows several video files and pdfs. How are those handled?

**Comment by sbesson** [comment]
All binaries are managed completely manually and this remains a requirement until we come up with a better solution. Just realized while talking to @jburel that this playbook does not make the folders group-writeable (and ideally with sticky bit)

**Comment by sbesson** [comment]
Merging to test the work flow with @jburel

**Pull request merged**
