### PR TITLE
Prometheus monitoring agents

### PR DESCRIPTION
**Pull request by manics**
This is an attempt to extract using git-filter the client-side (prometheus exporter) parts of https://github.com/openmicroscopy/prod-playbooks/pull/70

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [TRAINING-merge#37](https://ci.openmicroscopy.org/job/TRAINING-merge/37/). See the [console output](https://ci.openmicroscopy.org/job/TRAINING-merge/37/consoleText) for more details.
Possible conflicts:
  - PR #70 manics 'Outreach monitoring'
    - omero/training-server/playbook.yml
  - PR #74 manics 'Revert shared webapp mapr config'
    - omero/training-server/playbook.yml

--conflicts

**Comment by joshmoore** [comment]
gh-70 has now been excluded so this should no longer be conflicting.

**Comment by joshmoore** [comment]
see https://github.com/openmicroscopy/prod-playbooks/pull/73#issuecomment-397230421 regarding:

```
+# TODO: change to prod-omero
+- hosts: pub-omero.openmicroscopy.org,outreach.openmicroscopy.org
+#- hosts: prod-omero
```

This is a temporary fix to deal with the fact that we don't have a clear staging/production separation for the `prod-omero` host group. An upcoming (approx. next week) PR will revert this change to apply the changes to all prod-omero hosts. The longer-term goal is to not need such small fixer PRs against this repo in favor of using the inventories for the differentiation.

**Comment by joshmoore** [comment]
Assumed to be a no-op against pub-omero and outreach. To be confirmed via the upcoming site.yml.

**Pull request merged**
