### PR TITLE
outreach and monitoring top-level site.yml

### PR DESCRIPTION
**Pull request by manics**
omero-monitoring-agents.yml is now part of the top-level site.yml

Also adds some basic tests for the outreach server.

### CODE REVIEW

**Comment by manics** [comment]
Reviewing the check-mode diffs for site.yml:

Looks like https://github.com/openmicroscopy/prod-playbooks/pull/59 wasn't deployed (sorts config statements to prevent churn):
```
TASK [openmicroscopy.omero-web : omero web | configuration 00-omero-web.omero] *
**
--- before: /opt/omero/web/config/00-omero-web.omero
+++ after: /var/folders/z0/tv7cs0n16m54ytpp_2tsk2c9w3bcxl/T/tmp7gsaXm/00-omero-w
eb-omero.j2

[REDACTED]

changed: [ns-web-pub.openmicroscopy.org]
--- before: /opt/omero/web/config/00-omero-web.omero
+++ after: /var/folders/z0/tv7cs0n16m54ytpp_2tsk2c9w3bcxl/T/tmpT2Ytnu/00-omero-w
eb-omero.j2

[REDACTED]

changed: [ns-web.openmicroscopy.org]



TASK [openmicroscopy.omero-web : omero web | configuration 00-omero-web.omero] *
**
--- before: /opt/omero/web/config/00-omero-web.omero
+++ after: /var/folders/z0/tv7cs0n16m54ytpp_2tsk2c9w3bcxl/T/tmprIHDMv/00-omero-w
eb-omero.j2

[REDACTED]

changed: [ome-demoserver.openmicroscopy.org]
--- before: /opt/omero/web/config/00-omero-web.omero
+++ after: /var/folders/z0/tv7cs0n16m54ytpp_2tsk2c9w3bcxl/T/tmpSJ1afa/00-omero-w
eb-omero.j2

[REDACTED]

changed: [pub-omero.openmicroscopy.org]
```

Expected (https://github.com/openmicroscopy/prod-playbooks/pull/73#issuecomment-397230421):
```
TASK [NGINX - create nested includes directory] ********************************
--- before
+++ after
@@ -1,4 +1,4 @@
 {
     "path": "/etc/nginx/conf.d-nested-includes",
-    "state": "absent"
+    "state": "directory"
 }

changed: [ome-demoserver.openmicroscopy.org]
ok: [pub-omero.openmicroscopy.org]

TASK [NGINX - omero-web.conf nested includes] **********************************
--- before: /etc/nginx/conf.d/omero-web.conf (content)
+++ after: /etc/nginx/conf.d/omero-web.conf (content)
@@ -3,6 +3,7 @@
 }

 server {
+    include /etc/nginx/conf.d-nested-includes/*.conf;
     listen 80;
     listen 443 ssl;
     server_name $hostname;

changed: [ome-demoserver.openmicroscopy.org]
ok: [pub-omero.openmicroscopy.org]
```

Looks like https://github.com/openmicroscopy/prod-playbooks/pull/59 wasn't deployed?
```
TASK [openmicroscopy.omero-server : omero server | systemd service] ************
--- before: /etc/systemd/system/omero-server.service
+++ after: /var/folders/z0/tv7cs0n16m54ytpp_2tsk2c9w3bcxl/T/tmpwy1tAo/systemd-system-omero-server-service.j2
@@ -8,6 +8,8 @@
 After=postgresql-9.6.service
 Requires=network.service
 After=network.service
+After=gpfs.service
+Requires=gpfs.service

 [Service]
 User=omero-x

changed: [ome-dundeeomero.openmicroscopy.org]
```

**Comment by joshmoore** [comment]
```
ansiblplaybook -i ../ansible/inventory/prod-hosts playbooks/site.yml --list-hosts

playbook: playbooks/site.yml

  play #1 (ns-webclients): ns-webclients	TAGS: []
    pattern: [u'ns-webclients']
    hosts (2):
      ns-web-pub.openmicroscopy.org
      ns-web.openmicroscopy.org

  play #2 (ome-demoservers): ome-demoservers	TAGS: []
    pattern: [u'ome-demoservers']
    hosts (2):
      pub-omero.openmicroscopy.org
      ome-demoserver.openmicroscopy.org

  play #3 (ome-dundeeomero.openmicroscopy.org): ome-dundeeomero.openmicroscopy.org	TAGS: []
    pattern: [u'ome-dundeeomero.openmicroscopy.org']
    hosts (1):
      ome-dundeeomero.openmicroscopy.org

  play #4 (outreach.openmicroscopy.org): outreach.openmicroscopy.org	TAGS: []
    pattern: [u'outreach.openmicroscopy.org']
    hosts (1):
      outreach.openmicroscopy.org

  play #5 (outreach.openmicroscopy.org): outreach.openmicroscopy.org	TAGS: []
    pattern: [u'outreach.openmicroscopy.org']
    hosts (1):
      outreach.openmicroscopy.org

  play #6 (pub-omero.openmicroscopy.org,outreach.openmicroscopy.org): pub-omero.openmicroscopy.org,outreach.openmicroscopy.org	TAGS: []
    pattern: [u'pub-omero.openmicroscopy.org,outreach.openmicroscopy.org']
    hosts (2):
      pub-omero.openmicroscopy.org
      outreach.openmicroscopy.org

  play #7 (pub-omero.openmicroscopy.org,outreach.openmicroscopy.org): pub-omero.openmicroscopy.org,outreach.openmicroscopy.org	TAGS: []
    pattern: [u'pub-omero.openmicroscopy.org,outreach.openmicroscopy.org']
    hosts (2):
      pub-omero.openmicroscopy.org
      outreach.openmicroscopy.org

  play #8 (pub-omero.openmicroscopy.org,outreach.openmicroscopy.org): pub-omero.openmicroscopy.org,outreach.openmicroscopy.org	TAGS: []
    pattern: [u'pub-omero.openmicroscopy.org,outreach.openmicroscopy.org']
    hosts (2):
      pub-omero.openmicroscopy.org
      outreach.openmicroscopy.org
```

There's an error running the whole thing (in check mode) unrelated to this PR:

```
TASK [openmicroscopy.lvm-partition : storage | format] ********************************************************************************
fatal: [ns-web.openmicroscopy.org]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: {{ provision_root_filesystem }}: 'provision_root_filesystem' is undefined\n\nThe error appears to have been in '/Users/jamoore/opt/management_tools/prod/playbooks/vendor/openmicroscopy.lvm-partition/tasks/main.yml': line 13, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: storage | format\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: {{ provision_root_filesystem }}: 'provision_root_filesystem' is undefined"}
```


So,

 * checking out the new credentials
 * running with MT-786
 * modifying site.yml just run this PR in check-mode (only showing changes/errors):

```
TASK [openmicroscopy.omero-prometheus-exporter : omero prometheus exporter | install omero-prometheus-tools] **************************
changed: [outreach.openmicroscopy.org]
changed: [pub-omero.openmicroscopy.org]

TASK [openmicroscopy.omero-prometheus-exporter : omero prometheus exporter | configure service] ***************************************
fatal: [pub-omero.openmicroscopy.org]: FAILED! => {"changed": false, "msg": "AnsibleError: {{ secret_omero_prometheus_exporter_omero_user | default('root') }}: {{ lookup('passwordstore', 'ops/{{ inventory_hostname }} subkey=omero_monitoring_user') }}: An unhandled exception occurred while running the lookup plugin 'passwordstore'. Error was a <class 'ansible.errors.AnsibleError'>, original message: passname: ops/pub-omero.openmicroscopy.org not found, use create=True"}
ok: [outreach.openmicroscopy.org]


RUNNING HANDLER [openmicroscopy.omero-prometheus-exporter : restart prometheus-omero-exporter] ****************************************
changed: [outreach.openmicroscopy.org]

PLAY RECAP ****************************************************************************************************************************
outreach.openmicroscopy.org : ok=36   changed=2    unreachable=0    failed=0
pub-omero.openmicroscopy.org : ok=19   changed=1    unreachable=0    failed=1
```

**Comment by manics** [comment]
```
TASK [openmicroscopy.lvm-partition : storage | format] ********************************************************************************
fatal: [ns-web.openmicroscopy.org]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: {{ provision_root_filesystem }}: 'provision_root_filesystem' is undefined\n\nThe error appears to have been in '/Users/jamoore/opt/management_tools/prod/playbooks/vendor/openmicroscopy.lvm-partition/tasks/main.yml': line 13, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: storage | format\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: {{ 
```
I didn't see this when I ran check mode. @kennethgillen any ideas?

```
TASK [openmicroscopy.omero-prometheus-exporter : omero prometheus exporter | install omero-prometheus-tools] **************************
changed: [outreach.openmicroscopy.org]
changed: [pub-omero.openmicroscopy.org]
```
Probably the usual false positive with pip

```
TASK [openmicroscopy.omero-prometheus-exporter : omero prometheus exporter | configure service] ***************************************
fatal: [pub-omero.openmicroscopy.org]: FAILED! => {"changed": false, "msg": "AnsibleError: {{ secret_omero_prometheus_exporter_omero_user | default('root') }}: {{ lookup('passwordstore', 'ops/{{ inventory_hostname }} subkey=omero_monitoring_user') }}: An unhandled exception occurred while running the lookup plugin 'passwordstore'. Error was a <class 'ansible.errors.AnsibleError'>, original message: passname: ops/pub-omero.openmicroscopy.org not found, use create=True"}
ok: [outreach.openmicroscopy.org]
```
Are you sure passwordstore is up to date?

**Comment by joshmoore** [comment]
> Are you sure passwordstore is up to date?

Ah, this is likely my failing to set PASSWORD_STORE_DIR. I'll re-run.

**Comment by joshmoore** [comment]
Merging to unblock.

**Pull request merged**
