### PR TITLE
549 upgrades to prod OMERO plus new SSL deployment mechanism

### PR DESCRIPTION
**Pull request by kennethgillen**
549 upgrades to prod OMERO plus new SSL deployment mechanism

Supporting (private) config at https://github.com/openmicroscopy/management_tools/pull/862

### CODE REVIEW

**Comment by kennethgillen** [comment]
Demo server deployment worked well @ 

prod-playbooks at e923f94
management tools at 369c052

**Comment by kennethgillen** [comment]
ome-dundeeomero deployed at `60f3316`, but NGINX didn't automatically start. TODO.

**Comment by kennethgillen** [comment]
ns-web and ns-web-pub also deployed at `60f3316 `

**Comment by sbesson** [comment]
- :+1: for the production server upgrade
- :+1: for updating this role to consume the upstream role and the `openmicroscopy.ssl-certificate` bump
- Travis flagged a few formatting issues associated (trailing whitespaces) that will need to be resolved

**Comment by kennethgillen** [comment]
Regarding the last, 

`wsgi_workers` is [scaled in accordance with OMERO.web deployment docs](https://github.com/openmicroscopy/management_tools/blame/7509a180c919ca9c86267850977375376bea9340/ansible/inventory/group_vars/ns-webclients.yml#L28) with number of CPUs.

Number of CPUs was updated recently on the host, and so the number of workers was recalculated and reconfigured by Ansible during the deployment.

**Comment by sbesson** [comment]
All green. ANything else here @kennethgillen ?

**Comment by kennethgillen** [comment]
No sir, for this set of upgrades we're done. Thanks @sbesson.

**Pull request merged**
