### PR TITLE
Bump version to 5.4.5

### PR DESCRIPTION
**Pull request by jburel**
Bump version to 5.4.5

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1844](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1844/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1844/consoleText) for more details.
Possible conflicts:
  - PR #53 kennethgillen 'new server pub-omero.openmicroscopy.org'
    - ome-demoserver.yml

--conflicts

**Comment by sbesson** [comment]
@kennethgillen this has been deployed on production and should be ready to merge right?

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1845](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1845/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1845/consoleText) for more details.
Possible conflicts:
  - PR #53 kennethgillen 'new server pub-omero.openmicroscopy.org'
    - ome-demoserver.yml

--conflicts

**Comment by kennethgillen** [comment]
@sbesson - yep, changes are good, and deployed yesterday evening.

**Comment by kennethgillen** [comment]
👍

**Pull request merged**
