### PR TITLE
Fix link not to point to jburel

### PR DESCRIPTION
**Pull request by pwalczysko**
This is a follow-up of the outreach updating PR, see https://github.com/openmicroscopy/prod-playbooks/pull/67#issuecomment-391861695

cc @jburel

### CODE REVIEW

**Comment by jburel** [comment]
You can replace master by v0.1.0
when ``training-scripts`` is tagged today you will be able to run the playbook

**Comment by manics** [comment]
If you rerun the playbook can you include https://github.com/openmicroscopy/prod-playbooks/pull/69 otherwise the https setup will be lost.

**Comment by jburel** [comment]
training-scripts has been tagged https://github.com/ome/training-scripts/releases/tag/v0.1.0

**Comment by pwalczysko** [comment]
Do not know how to restart travis. It seems to fail on the link with the ``v0.1.0`` which is now okay already. But, I do not have the ``little buttons`` in the travis UI to rerun the build, although I am logged in....

**Comment by jburel** [comment]
restarted

**Comment by pwalczysko** [comment]
The playbook was run on outreach just now (with https://github.com/openmicroscopy/prod-playbooks/pull/69 merged in locally). All seems well on outreach server, https as well as the ``batch_roi_export.py`` are okay.

**Comment by jburel** [comment]
Merging so we can tag the training-repos

**Pull request merged**
