### PR TITLE
cyberessentials: omero-web-patch-settings.yml: SESSION_COOKIE_SECURE = True

### PR DESCRIPTION
**Pull request by manics**
This might be needed too? https://github.com/openmicroscopy/prod-playbooks/blob/96170aab24bd118b8f154c28c0919f0551e93102/omero/omero-web-patch-settings.yml#L16-L18

### CODE REVIEW

**Comment by manics** [comment]
https://github.com/openmicroscopy/prod-playbooks/pull/154 has priority

**Comment by manics** [comment]
Deployed to pub-omero

**Comment by sbesson** [comment]
Is a minimal functional review of the Web client and the deployed Web apps a good next step here? Or is there more to be done?

**Comment by manics** [comment]
Just checking OMERO.web and web-apps should be enough, since if https is enforced this property should be redundant.

**Comment by pwalczysko** [comment]
On pub-omero, went through following apps:

   - FPBioimage
   - OMERO.figure (basic workflow, labels, zooming, ROI drawing, loading of ROIs, saving, export, viewing of figures of others)
   - OMERO.iviewer (basic viewing big and small, multi-z and t, drawing, saving, deleting ROIs, viewing of others data, saving rnd settings)
   - OMERO.parade (full workflow on idr0021, with graph, table and filtering for ROIs and KVPs)
   - Tag Serach
   - Auto Tagger
 
In OMERO.web, went through viewing, annotating and Preview, imported also a plate

All passed

Ready to merge FMPOV

**Comment by manics** [comment]
Deployed to demo, ns-web and ns-web-pub

**Pull request merged**
