### PR TITLE
Nginx proxy role bump (www)

### PR DESCRIPTION
**Pull request by manics**
The role reverts the breaking log format change, so this is now defined as a parameter.
- See https://github.com/openmicroscopy/ansible-role-nginx-proxy/pull/21

### CODE REVIEW

**Comment by sbesson** [comment]
Thanks for opening the PR. I am not sure the custom NGINX format is required for the `www` server which has only 1 host. No objection to dropping 24d0745

**Comment by manics** [comment]
`ome-www` already has the new format from `1.8.0`, I can revert it but it means there'll have been an intervening period where the logs would've been in the other format. If we're not doing any log analysis on that box that won't matter.

**Comment by sbesson** [comment]
Unfortunately, we do already have a mixture of logs into 2 formats on this server. I do not know the `ome-www` logs are analyzed at the moment otherwise we would probably have flagged the log format change. If we do so, we will need to handle both variations.
Unless @joshmoore remembers specific reason not to do so, my vote still goes towards reverting the log format to using the default format.

**Comment by manics** [comment]
No one objected so I've reverted the last commit

**Comment by sbesson** [comment]
https://galaxy.ansible.com/openmicroscopy/nginx-proxy `1.9.0` is now tagged

**Comment by sbesson** [comment]
Thank you. Merging and proposing to schedule the redeployment of www tomorrow with the new format.

**Pull request merged**
