### PR TITLE
Nightshade server and web prometheus exporters

### PR DESCRIPTION
**Pull request by manics**
- The equivalent of https://github.com/openmicroscopy/prod-playbooks/pull/73 (nginx omero-web.conf nested includes) for nightshade server and webclients.
- Install prometheus agents on nightshade server and web

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [TRAINING-merge#40](https://ci.openmicroscopy.org/job/TRAINING-merge/40/). See the [console output](https://ci.openmicroscopy.org/job/TRAINING-merge/40/consoleText) for more details.
Possible conflicts:
  - PR #78 manics 'Omero firewall (iptables)'
    - omero/omero-monitoring-agents.yml

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1923](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1923/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1923/consoleText) for more details.
Possible conflicts:
  - PR #78 manics 'Omero firewall (iptables)'
    - omero/omero-monitoring-agents.yml

--conflicts

**Comment by manics** [comment]
Rebased

**Comment by kennethgillen** [comment]
```
2018-06-27 14:37 LS27172:~ kenny$ cat pr-changes | grep -C 1 'changed:'
TASK [NGINX - create nested includes directory] ***************************************************************************************************************************************
changed: [ome-dundeeomero.openmicroscopy.org]

TASK [NGINX - Configuration] **********************************************************************************************************************************************************
changed: [ome-dundeeomero.openmicroscopy.org]

RUNNING HANDLER [openmicroscopy.omero-common : restart nginx] *************************************************************************************************************************
changed: [ome-dundeeomero.openmicroscopy.org]

--
TASK [openmicroscopy.ice : zeroc ice | pip install packages] **************************************************************************************************************************
changed: [ome-dundeeomero.openmicroscopy.org]

--
TASK [Create a figure scripts directory] **********************************************************************************************************************************************
changed: [ome-dundeeomero.openmicroscopy.org]

TASK [Download the Figure_To_Pdf.py script] *******************************************************************************************************************************************
changed: [ome-dundeeomero.openmicroscopy.org]

```

👍 good to merge - looks like it matches up with what was done on demo.

@joshmoore - could you please press the button before this evening's agent install & upgrade.

**Comment by kennethgillen** [comment]
Thanks.

**Pull request merged**
